name: Build Typst

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Github Action for Typst
      uses: lvignoli/typst-action@v0.1
      with:
        input_file: template/main.typ
        output_file: template/main.pdf
