name: Build Typst

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Typst
      run: cargo install typst-cli --verbose

    - name: Build Typst document
      run: typst build  template/main.typ

    - name: Run Typst tests
      run: typst check template/main.typ --verbose
